/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.ClienteDao;
import models.ClienteVo;

/**
 *
 * @author jumbo170
 */
public class ClienteView extends javax.swing.JFrame {

    DefaultTableModel modelo;

    /**
     * Creates new form ClienteView
     */
    public ClienteView() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        this.listar();
    }

    void listar() throws SQLException {
        Object[] cliente = new Object[5];
        modelo = (DefaultTableModel) jTableClientes.getModel();
        ClienteDao clienteDao = new ClienteDao();
        List<ClienteVo> clientes = clienteDao.list();
        clientes.stream().forEach(client -> {
            cliente[0] = client.getIdcliente();
            cliente[1] = client.getCedulaCliente();
            cliente[2] = client.getNombre();
            cliente[3] = client.getTelefono();
            if (client.getEstado() == true) {
                cliente[4] = "Activo";
            } else {
                cliente[4] = "Inactivo";
            }
            modelo.addRow(cliente);
        });
        jTableClientes.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCedula2 = new javax.swing.JLabel();
        jTextFieldCedulaCliente = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonCliente = new javax.swing.JButton();
        jTextFieldTelefonoCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jButtonDeleteClient = new javax.swing.JButton();
        jButtonEditClient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 555));
        setName("Cliente"); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 139, 255));
        jLabel1.setText("Lista de Clientes");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 139, 255));
        jLabel2.setText("Clientes");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 139, 255));
        jLabel3.setText("Agregar Cliente");

        jLabelCedula.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelCedula.setForeground(new java.awt.Color(0, 64, 222));
        jLabelCedula.setText("Cédula");

        jLabelNombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 64, 222));
        jLabelNombre.setText("Nombre");

        jLabelCedula2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelCedula2.setForeground(new java.awt.Color(0, 64, 222));
        jLabelCedula2.setText("Teléfono");

        jTextFieldCedulaCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldCedulaCliente.setForeground(new java.awt.Color(26, 189, 203));
        jTextFieldCedulaCliente.setBorder(null);
        jTextFieldCedulaCliente.setCaretColor(new java.awt.Color(26, 189, 203));
        jTextFieldCedulaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaClienteActionPerformed(evt);
            }
        });

        jTextFieldNombre.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(26, 189, 203));
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.setCaretColor(new java.awt.Color(26, 189, 203));

        jButtonCliente.setBackground(new java.awt.Color(0, 139, 255));
        jButtonCliente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCliente.setText("Guardar Cliente");
        jButtonCliente.setBorder(null);
        jButtonCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonClienteMouseEntered(evt);
            }
        });
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });

        jTextFieldTelefonoCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldTelefonoCliente.setForeground(new java.awt.Color(26, 189, 203));
        jTextFieldTelefonoCliente.setBorder(null);
        jTextFieldTelefonoCliente.setCaretColor(new java.awt.Color(26, 189, 203));

        jTableClientes.setForeground(new java.awt.Color(0, 139, 255));
        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Cédula", "Nombre", "Teléfono", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTableClientes);

        jButtonDeleteClient.setBackground(new java.awt.Color(212, 0, 0));
        jButtonDeleteClient.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonDeleteClient.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteClient.setText("Eliminar Cliente");
        jButtonDeleteClient.setBorder(null);
        jButtonDeleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteClientActionPerformed(evt);
            }
        });

        jButtonEditClient.setBackground(new java.awt.Color(0, 222, 222));
        jButtonEditClient.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonEditClient.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditClient.setText("Cambiar Estado");
        jButtonEditClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(176, 176, 176))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCedula2)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelCedula)
                    .addComponent(jTextFieldCedulaCliente)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jTextFieldTelefonoCliente)
                    .addComponent(jButtonCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(jLabel2)
                .addGap(64, 64, 64)
                .addComponent(jButtonDeleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonEditClient, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditClient, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabelCedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButtonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCedulaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaClienteActionPerformed

    private void jButtonClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClienteMouseEntered

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        // TODO add your handling code here:
        try {
// TODO add your handling code here:
            registerClient();
        } catch (SQLException ex) {
            Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jButtonDeleteClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteClientActionPerformed
        // TODO add your handling code here:
        String cedula = JOptionPane.showInputDialog("Ingrese el numero de cuenta para eliminarla", null);
        try {
            ClienteDao clienteDao = new ClienteDao();
            clienteDao.delete(cedula);
            this.clearTable();
            this.listar();
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_jButtonDeleteClientActionPerformed

    private void jButtonEditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditClientActionPerformed
        // TODO add your handling code here:
        String cedula = JOptionPane.showInputDialog("Porfavor Ingrese el número de cuenta", null);
        System.out.println(cedula);
        ClienteDao clienteDao = new ClienteDao();
        try {
            clienteDao.changeStatus(cedula);
            this.clearTable();
            this.listar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "El número de cuenta no existe");
            Logger
                    .getLogger(CuentaView.class
                            .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEditClientActionPerformed

    public void registerClient() throws SQLException {
        if (!jTextFieldCedulaCliente.getText().isEmpty()
                && !jTextFieldNombre.getText().isEmpty()
                && !jTextFieldTelefonoCliente.getText().isEmpty()) {
            String CedulaCliente = jTextFieldCedulaCliente.getText();
            String Nombre = jTextFieldNombre.getText();
            String Telefono = jTextFieldTelefonoCliente.getText();
            boolean Estado = true;

            ClienteDao clientedao = new ClienteDao();

            ClienteVo cliente = new ClienteVo(CedulaCliente, Nombre, Telefono, Estado);

            try {
                clientedao.save(cliente);
                JOptionPane.showMessageDialog(null, "Registro");
                this.clearTable();
            } catch (SQLException e) {
                System.out.println(e.toString());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Los Campos no pueden estar vacios. Porfavor llenelos");
        }
        this.listar();
    }

    void clearTable() {
        for (int i = 0; i < jTableClientes.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ClienteView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonDeleteClient;
    private javax.swing.JButton jButtonEditClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCedula2;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextFieldCedulaCliente;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
